/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/

int main(void)
{
	char msg1[]="Hello How are you?";

	char *pmsg2 = "ronak.com";
	msg1[0]='L';


	printf("Message is : %s\n",msg1);
	printf("Message is : %s\n",pmsg2);
	printf("Value  of msg1 variable is = %p\n",&msg1);

	printf("Address of pmsg2 variable is = %p\n",&pmsg2);
	printf("Value  of pmsg2 variable is = %p\n",pmsg2);

	for(;;);

}
