

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

int main(void)
{
	uint32_t *pClkctrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;

	uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
	uint32_t *pPortAInReg = (uint32_t*)0x40020010;



	//Enable the clock for GPIOD, GPIOA peripheral in the AHB1ENR
	*pClkctrlReg |= (1<<3); //for GPIOD
	*pClkctrlReg |= (1<<0);//for GPIOA


	//Configure PD12 pin as output
	*pPortDModeReg &= ~(3<<24);
	*pPortDModeReg &= ~(3<<26);
	*pPortDModeReg &= ~(3<<28);
	*pPortDModeReg &= ~(3<<30);
	//make 24th bit position as 1 (SET)
		*pPortDModeReg |= ( 1 << 24);
		*pPortDModeReg |= ( 1 << 26);
		*pPortDModeReg |= ( 1 << 28);
		*pPortDModeReg |= ( 1 << 30);

	//configure PA0 pin as input mode(GPIOA MODE REGISTER)
	*pPortAModeReg &= ~(3<<0);

	while(1){

		//read the pin status of the pin PA0(GPIO INPUT DATA REGISTER)
		uint8_t pinStatus = (uint8_t)*pPortAInReg & 0x1;

		if(pinStatus){
			//turn On the LED
			*pPortDOutReg |= (0xF<<12); // tomake all LED or PIN 12,13,14,15 HIGH
		}else{
			//turn OFF the LED
			*pPortDOutReg &= ~(0xF<<12);
		}
	}


}
