/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

int main(void)
{
	uint32_t *pClkctrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;

	//Enable the clock for GPIOD peripheral in the AHB1ENR
	*pClkctrlReg |= (1<<3);//*pClkctrlReg |= 0x08;

	//Configure the mode of the pin as output
	//clear the 24th and 25th bit position CLEAR
	*pPortDModeReg &= ~( 3 << 24);//*pPortDModeReg &= 0xFCFFFFFF;

	//make 24th bit position as 1 SET
	*pPortDModeReg |= ( 1 << 24);//*pPortDModeReg |= 0x01000000;
	while(1){
		//Configure the 12th pin HIGH as IO
		*pPortDOutReg |= (1<<12);//*pPortDOutReg |= 0x1000;
		for(uint32_t i=0;i<250000;i++); //Delay
		//Configure the 12th pin LOW
		*pPortDOutReg &= ~(1<<12);
		for(uint32_t i=0;i<250000;i++); //Delay
	}
}
